server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 9
      maxActive: 100
      maxWait: 60000
      min-idle: 5

  aop:
    proxy-target-class: false

#db:
#  schema:
#    database: test1



mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml




logging:
  level:
    com.ex: debug

