server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Aa+123456
#    druid:
#      username: root
#      password: Aa+123456
#      url: jdbc:mysql://localhost:3306/test?useSSL=false
#      driver-class-name: com.mysql.cj.jdbc.Driver


