server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      #    username: remote_user
    username: root
    password: Aa+123456

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 9
      maxActive: 100
      maxWait: 60000
      min-idle: 5
  aop:
    proxy-target-class: false
  devtools:
    restart:
      enabled: true #设置开启热部署
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**
    livereload:
      enabled: true

  #springboot 整合quartz框架
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyQuartzScheduler
          threadPool:
            threadCount: 5
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true


mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml




logging:
  level:
    com.ex: debug

