server:
  port: 9999
spring:
#  datasource:
#    url: jdbc:mysql://43.139.10.159:3306/test?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
##    username: remote_user
#    username: root
#    password: Aa+123456
#
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initialSize: 9
#      maxActive: 100
#      maxWait: 60000
#      min-idle: 5

##################################################################################
#      min-evictable-idle-time-millis: 30000
#      validation-query-timeout: 1000
#      test-on-borrow: false
#      test-on-return: false
#      max-pool-prepared-statement-per-connection-size: -1
#      use-global-data-source-stat: false
#      time-between-log-stats-millis: 60000
##      connect-properties: druid.stat.mergeSql=true;druid.stat.sqlowSqlMillis=5000

##################################################################################

#
#      connection-properties: druid.stat.mergeSql=true;druid.stat.sqlowSqlMillis=5000

#    url: jdbc:mysql://localhost:3306/test?useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Aa+123456

#mybatis:
#  mapper-locations: classpath:/mappers/*/*-Mapper.xml


#  aop:
#    proxy-target-class: false


#  devtools:
#    restart:
#      enabled: true #设置开启热部署
#      additional-paths: src/main/java
#      additional-exclude: WEB-INF/**
#    livereload:
#      enabled: true



#db:
#  schema:
#    database: test1



mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml




logging:
  level:
    com.ex: debug

